# Generated by Django 2.2.4 on 2019-11-19 04:27

import comics.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0002_users_portrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookename', models.CharField(max_length=20)),
                ('paints', models.ImageField(upload_to=comics.models.paints_upload_to)),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Users')),
            ],
            options={
                'db_table': 'comics',
            },
        ),
    ]
